### ISSUE TITLE
[Critical] User rights and ASGI application issues on backend

### ISSUE THREAD

**Issue by ioffem** [jdi-testing/jdn-ai#364]
JDN v 3.1.153
Back-end v 2022-02-12-11.36.19
Chrome

1) open https://cbracco.github.io/html5-test-page/
2) open JDN tab
3) new page object (material UI should be selected)
4) generate 
5) immediately select generated locator and confirm
6) new page object (material UI should be selected)
7) generate and wait

AR: backend was broken after long pause (info from terminal was added to comments)
ER: new page objects generating

**Comment by ioffem** [comment]
Attaching to jdi-qasp-ml-api, jdi-qasp-ml-celery, jdi-qasp-ml-redis
jdi-qasp-ml-redis   | 1:C 28 Mar 2022 07:00:51.703 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
jdi-qasp-ml-redis   | 1:C 28 Mar 2022 07:00:51.703 # Redis version=6.2.6, bits=64, commit=00000000, modified=0, pid=1, just started
jdi-qasp-ml-redis   | 1:C 28 Mar 2022 07:00:51.703 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
jdi-qasp-ml-redis   | 1:M 28 Mar 2022 07:00:51.704 * monotonic clock: POSIX clock_gettime
jdi-qasp-ml-redis   | 1:M 28 Mar 2022 07:00:51.704 * Running mode=standalone, port=6379.
jdi-qasp-ml-redis   | 1:M 28 Mar 2022 07:00:51.704 # Server initialized
jdi-qasp-ml-redis   | 1:M 28 Mar 2022 07:00:51.705 * Loading RDB produced by version 6.2.6
jdi-qasp-ml-redis   | 1:M 28 Mar 2022 07:00:51.705 * RDB age 13 seconds
jdi-qasp-ml-redis   | 1:M 28 Mar 2022 07:00:51.705 * RDB memory usage when created 1.43 Mb
jdi-qasp-ml-redis   | 1:M 28 Mar 2022 07:00:51.707 # Done loading RDB, keys loaded: 704, keys expired: 0.
jdi-qasp-ml-redis   | 1:M 28 Mar 2022 07:00:51.707 * DB loaded from disk: 0.002 seconds
jdi-qasp-ml-redis   | 1:M 28 Mar 2022 07:00:51.707 * Ready to accept connections
jdi-qasp-ml-api     | 2022-03-28 07:00:52,122 -INFO - config.py:31 - Module utils.config was loaded
jdi-qasp-ml-celery  |  
jdi-qasp-ml-celery  |  -------------- celery@c7970deb3e69 v5.1.2 (sun-harmonics)
jdi-qasp-ml-celery  | --- ***** ----- 
jdi-qasp-ml-celery  | -- ******* ---- Linux-5.10.76-linuxkit-x86_64-with-debian-10.11 2022-03-28 07:00:52
jdi-qasp-ml-celery  | - *** --- * --- 
jdi-qasp-ml-celery  | - ** ---------- [config]
jdi-qasp-ml-celery  | - ** ---------- .> app:         app.main:0x7f137b2de590
jdi-qasp-ml-celery  | - ** ---------- .> transport:   redis://redis:6379//
jdi-qasp-ml-celery  | - ** ---------- .> results:     redis://redis:6379/
jdi-qasp-ml-celery  | - *** --- * --- .> concurrency: 4 (prefork)
jdi-qasp-ml-celery  | -- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
jdi-qasp-ml-celery  | --- ***** ----- 
jdi-qasp-ml-celery  |  -------------- [queues]
jdi-qasp-ml-celery  |                 .> celery           exchange=celery(direct) key=celery
jdi-qasp-ml-celery  |                 
jdi-qasp-ml-celery  | 
jdi-qasp-ml-celery  | [tasks]
jdi-qasp-ml-celery  |   . app.tasks.task_schedule_xpath_generation
jdi-qasp-ml-celery  | 
jdi-qasp-ml-celery  | /usr/local/lib/python3.7/site-packages/celery/platforms.py:835: SecurityWarning: You're running the worker with superuser privileges: this is
jdi-qasp-ml-celery  | absolutely not recommended!
jdi-qasp-ml-celery  | 
jdi-qasp-ml-celery  | Please specify a different user using the --uid option.
jdi-qasp-ml-celery  | 
jdi-qasp-ml-celery  | User information: uid=0 euid=0 gid=0 egid=0
jdi-qasp-ml-celery  | 
jdi-qasp-ml-celery  |   uid=uid, euid=euid, gid=gid, egid=egid,
jdi-qasp-ml-celery  | [2022-03-28 07:00:52,259: INFO/MainProcess] Connected to redis://redis:6379//
jdi-qasp-ml-celery  | [2022-03-28 07:00:52,263: INFO/MainProcess] mingle: searching for neighbors
jdi-qasp-ml-api     | 2022-03-28 07:00:53,086 -INFO - common.py:119 - Module utils.common is loaded...
jdi-qasp-ml-api     | 2022-03-28 07:00:53,087 -INFO - hidden.py:70 - hidden module is loaded
jdi-qasp-ml-api     | 2022-03-28 07:00:53,089 -INFO - features_builder.py:780 - feature_bilder module is loaded...
jdi-qasp-ml-celery  | [2022-03-28 07:00:53,277: INFO/MainProcess] mingle: all alone
jdi-qasp-ml-celery  | [2022-03-28 07:00:53,296: INFO/MainProcess] celery@c7970deb3e69 ready.
jdi-qasp-ml-api     | 2022-03-28 07:00:53,371 -INFO - dataset.py:272 - dataset module is loaded...
jdi-qasp-ml-api     | 2022-03-28 07:00:53,413 -INFO - config.py:31 - Module utils.config was loaded
jdi-qasp-ml-api     | 2022-03-28 07:00:53,413 -INFO - common.py:618 - Module utils.common is loaded...
jdi-qasp-ml-api     | 2022-03-28 07:00:53,414 -INFO - hidden.py:121 - hidden module is loaded
jdi-qasp-ml-api     | 2022-03-28 07:00:53,415 -INFO - features_builder.py:350 - feature_bilder module is loaded...
jdi-qasp-ml-api     | 2022-03-28 07:00:53,416 -INFO - dataset_builder.py:245 - dataset package is loaded...
jdi-qasp-ml-api     | 2022-03-28 07:00:53,417 -INFO - dataset.py:313 - dataset module is loaded...
jdi-qasp-ml-api     | INFO:     Started server process [1]
jdi-qasp-ml-api     | INFO:     Waiting for application startup.
jdi-qasp-ml-api     | INFO:     Application startup complete.
jdi-qasp-ml-api     | INFO:     Uvicorn running on http://0.0.0.0:5000 (Press CTRL+C to quit)
jdi-qasp-ml-api     | INFO:     172.22.0.1:64928 - "GET /build HTTP/1.1" 200 OK
  0%|          | 0/1 [00:00<?, ?it/s, /jdi-qasp-ml/data/mui_dataset/df/202203280Build tree features: 100%|██████████| 4242/4242 [00:03<00:00, 1338.78it/s]
100%|██████████| 1/1 [00:05<00:00,  5.85s/it, /jdi-qasp-ml/data/mui_dataset/df/2100%|██████████| 1/1 [00:05<00:00,  5.85s/it, /jdi-qasp-ml/data/mui_dataset/df/20220328070100355260.pkl]2022-03-28 07:01:06,341 -INFO - dataset.py:165 - self.df.shape: (4242, 27)
jdi-qasp-ml-api     | 2022-03-28 07:01:06,342 -INFO - dataset.py:108 - Check for duplicates...
jdi-qasp-ml-api     | 2022-03-28 07:01:06,345 -INFO - dataset.py:112 - Check for duplicates is OK
jdi-qasp-ml-api     | 2022-03-28 07:01:06,372 -INFO - features_builder.py:383 - used column: tag_name
jdi-qasp-ml-api     | 2022-03-28 07:01:06,372 -INFO - features_builder.py:386 - loading /jdi-qasp-ml/MUI_model/model/ohe_tag_name.pkl
jdi-qasp-ml-api     | 2022-03-28 07:01:06,376 -INFO - features_builder.py:383 - used column: tag_name_parent
jdi-qasp-ml-api     | 2022-03-28 07:01:06,376 -INFO - features_builder.py:386 - loading /jdi-qasp-ml/MUI_model/model/ohe_tag_name.pkl
jdi-qasp-ml-api     | 2022-03-28 07:01:06,379 -INFO - features_builder.py:311 - tag_name: (4242, 8)
jdi-qasp-ml-api     | 2022-03-28 07:01:06,380 -INFO - features_builder.py:416 - used column: attributes
jdi-qasp-ml-api     | 
jdi-qasp-ml-api     | /usr/local/lib/python3.7/site-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator OneHotEncoder from version 1.0.1 when using version 0.24.1. This might lead to breaking code or invalid results. Use at your own risk.
jdi-qasp-ml-api     |   UserWarning)
jdi-qasp-ml-api     | /usr/local/lib/python3.7/site-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator OneHotEncoder from version 1.0.1 when using version 0.24.1. This might lead to breaking code or invalid results. Use at your own risk.
jdi-qasp-ml-api     |   UserWarning)
Extract "attributes": 100%|██████████| 4242/4242 [00:00<00:00, 15553.84it/s]2022-03-28 07:01:06,685 -INFO - features_builder.py:416 - used column: attributes_parent
jdi-qasp-ml-api     | 
Extract "attributes": 100%|██████████| 4242/4242 [00:00<00:00, 15795.26it/s]2022-03-28 07:01:06,986 -INFO - features_builder.py:326 - attributes_sm: (4242, 31)
jdi-qasp-ml-api     | 2022-03-28 07:01:06,986 -INFO - features_builder.py:455 - used column: attributes
jdi-qasp-ml-api     | 2022-03-28 07:01:06,986 -INFO - features_builder.py:460 - CountVectorizer and TfidfTransformer for class attribute exist. Loading...
jdi-qasp-ml-api     | 2022-03-28 07:01:07,136 -INFO - features_builder.py:455 - used column: attributes_parent
jdi-qasp-ml-api     | 2022-03-28 07:01:07,136 -INFO - features_builder.py:460 - CountVectorizer and TfidfTransformer for class attribute exist. Loading...
jdi-qasp-ml-api     | 2022-03-28 07:01:07,264 -INFO - features_builder.py:333 - class_sm: (4242, 914)
jdi-qasp-ml-api     | 2022-03-28 07:01:07,264 -INFO - features_builder.py:519 - used column: attributes
jdi-qasp-ml-api     | 2022-03-28 07:01:07,264 -INFO - features_builder.py:522 - loading /jdi-qasp-ml/MUI_model/model/ohe_type.pkl
jdi-qasp-ml-api     | 2022-03-28 07:01:07,268 -INFO - features_builder.py:519 - used column: attributes_parent
jdi-qasp-ml-api     | 2022-03-28 07:01:07,268 -INFO - features_builder.py:522 - loading /jdi-qasp-ml/MUI_model/model/ohe_type.pkl
jdi-qasp-ml-api     | 2022-03-28 07:01:07,271 -INFO - features_builder.py:340 - type_sm: (4242, 2)
jdi-qasp-ml-api     | 2022-03-28 07:01:07,272 -INFO - features_builder.py:554 - used column: attributes
jdi-qasp-ml-api     | 2022-03-28 07:01:07,272 -INFO - features_builder.py:557 - loading /jdi-qasp-ml/MUI_model/model/ohe_role.pkl
jdi-qasp-ml-api     | 2022-03-28 07:01:07,276 -INFO - features_builder.py:554 - used column: attributes_parent
jdi-qasp-ml-api     | 2022-03-28 07:01:07,276 -INFO - features_builder.py:557 - loading /jdi-qasp-ml/MUI_model/model/ohe_role.pkl
jdi-qasp-ml-api     | 2022-03-28 07:01:07,282 -INFO - features_builder.py:347 - role_sm: (4242, 8)
jdi-qasp-ml-api     | 2022-03-28 07:01:07,282 -INFO - features_builder.py:590 - used column: children_tags
jdi-qasp-ml-api     | 2022-03-28 07:01:07,282 -INFO - features_builder.py:594 - CountVectorizer and TfidfTransformer for children tags exist. Loading...
jdi-qasp-ml-api     | 2022-03-28 07:01:07,296 -INFO - features_builder.py:651 - used column: followers_tags
jdi-qasp-ml-api     | 2022-03-28 07:01:07,296 -INFO - features_builder.py:655 - CountVectorizer and TfidfTransformer for followers tags exist. Loading...
jdi-qasp-ml-api     | 2022-03-28 07:01:07,384 -INFO - dataset_collector.py:174 - X: (4242, 2009)
jdi-qasp-ml-api     | 
jdi-qasp-ml-api     | /usr/local/lib/python3.7/site-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator TfidfTransformer from version 1.0.1 when using version 0.24.1. This might lead to breaking code or invalid results. Use at your own risk.
jdi-qasp-ml-api     |   UserWarning)
jdi-qasp-ml-api     | /usr/local/lib/python3.7/site-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator TfidfVectorizer from version 1.0.1 when using version 0.24.1. This might lead to breaking code or invalid results. Use at your own risk.
jdi-qasp-ml-api     |   UserWarning)
jdi-qasp-ml-api     | /usr/local/lib/python3.7/site-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator OneHotEncoder from version 1.0.1 when using version 0.24.1. This might lead to breaking code or invalid results. Use at your own risk.
jdi-qasp-ml-api     |   UserWarning)
jdi-qasp-ml-api     | /usr/local/lib/python3.7/site-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator OneHotEncoder from version 1.0.1 when using version 0.24.1. This might lead to breaking code or invalid results. Use at your own risk.
jdi-qasp-ml-api     |   UserWarning)
jdi-qasp-ml-api     | /usr/local/lib/python3.7/site-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator OneHotEncoder from version 1.0.1 when using version 0.24.1. This might lead to breaking code or invalid results. Use at your own risk.
jdi-qasp-ml-api     |   UserWarning)
jdi-qasp-ml-api     | /usr/local/lib/python3.7/site-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator OneHotEncoder from version 1.0.1 when using version 0.24.1. This might lead to breaking code or invalid results. Use at your own risk.
jdi-qasp-ml-api     |   UserWarning)
jdi-qasp-ml-api     | /usr/local/lib/python3.7/site-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator CountVectorizer from version 1.0.1 when using version 0.24.1. This might lead to breaking code or invalid results. Use at your own risk.
jdi-qasp-ml-api     |   UserWarning)
jdi-qasp-ml-api     | /usr/local/lib/python3.7/site-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator TfidfTransformer from version 1.0.1 when using version 0.24.1. This might lead to breaking code or invalid results. Use at your own risk.
jdi-qasp-ml-api     |   UserWarning)
100%|██████████| 4242/4242 [00:01<00:00, 2817.22it/s]INFO:     172.22.0.1:64928 - "POST /mui-predict HTTP/1.1" 200 OK
jdi-qasp-ml-api     | INFO:     172.22.0.1:64928 - "GET /cpu-count HTTP/1.1" 200 OK
jdi-qasp-ml-api     | 
jdi-qasp-ml-api     | INFO:     ('172.22.0.1', 64930) - "WebSocket /ws" [accepted]
jdi-qasp-ml-api     | INFO:     connection open
jdi-qasp-ml-celery  | [2022-03-28 07:01:09,560: INFO/MainProcess] Task app.tasks.task_schedule_xpath_generation[e923a239-31f5-4243-bf95-67e909055b14] received
jdi-qasp-ml-celery  | [2022-03-28 07:01:09,648: INFO/MainProcess] Task app.tasks.task_schedule_xpath_generation[1a9819c6-442b-4c41-8ba3-82398b009b62] received
jdi-qasp-ml-celery  | /usr/local/lib/python3.7/site-packages/celery/platforms.py:835: SecurityWarning: You're running the worker with superuser privileges: this is
jdi-qasp-ml-celery  | absolutely not recommended!
jdi-qasp-ml-celery  | 
jdi-qasp-ml-celery  | Please specify a different user using the --uid option.
jdi-qasp-ml-celery  | 
jdi-qasp-ml-celery  | User information: uid=0 euid=0 gid=0 egid=0
jdi-qasp-ml-celery  | 
jdi-qasp-ml-celery  |   uid=uid, euid=euid, gid=gid, egid=egid,
jdi-qasp-ml-celery  | [2022-03-28 07:01:09,693: INFO/ForkPoolWorker-4] Task app.tasks.task_schedule_xpath_generation[e923a239-31f5-4243-bf95-67e909055b14] succeeded in 0.08823969999866677s: '//*[@class=\'SearchTypeahead-suggestions-r5x\']'
jdi-qasp-ml-celery  | [2022-03-28 07:01:09,700: INFO/MainProcess] Task app.tasks.task_schedule_xpath_generation[b5c24e8f-f75c-46d7-a6f7-1ee3ebb3d2e5] received
jdi-qasp-ml-celery  | [2022-03-28 07:01:09,758: INFO/MainProcess] Task app.tasks.task_schedule_xpath_generation[1f2830e1-97a3-4425-82e1-a292166f2293] received
jdi-qasp-ml-celery  | /usr/local/lib/python3.7/site-packages/celery/platforms.py:835: SecurityWarning: You're running the worker with superuser privileges: this is
jdi-qasp-ml-celery  | absolutely not recommended!
jdi-qasp-ml-celery  | 
jdi-qasp-ml-celery  | Please specify a different user using the --uid option.
jdi-qasp-ml-celery  | 
jdi-qasp-ml-celery  | User information: uid=0 euid=0 gid=0 egid=0
jdi-qasp-ml-celery  | 
jdi-qasp-ml-celery  |   uid=uid, euid=euid, gid=gid, egid=egid,
jdi-qasp-ml-celery  | [2022-03-28 07:01:09,806: INFO/ForkPoolWorker-2] Task app.tasks.task_schedule_xpath_generation[1a9819c6-442b-4c41-8ba3-82398b009b62] succeeded in 0.07633619999978691s: '//*[@class=\'Search-tabList-EY4\']'
jdi-qasp-ml-celery  | [2022-03-28 07:01:09,999: INFO/ForkPoolWorker-4] Task app.tasks.task_schedule_xpath_generation[b5c24e8f-f75c-46d7-a6f7-1ee3ebb3d2e5] succeeded in 0.2112422999998671s: '//*[@class=\'PrimaryNav-strip-Xyi js-nav-primary e2e-PrimaryNav\']/*[@class=\'PrimaryNav-coreNavigation-iAB\']'
jdi-qasp-ml-celery  | [2022-03-28 07:01:10,211: INFO/MainProcess] Task app.tasks.task_schedule_xpath_generation[2e9027ba-6a24-4c99-8838-3ac68bf9b36b] received
jdi-qasp-ml-celery  | [2022-03-28 07:01:10,454: INFO/MainProcess] Task app.tasks.task_schedule_xpath_generation[9cc48179-2dd8-4e82-ab0e-92f0b8a5abe5] received
jdi-qasp-ml-celery  | [2022-03-28 07:01:10,546: INFO/MainProcess] Task app.tasks.task_schedule_xpath_generation[7acbac86-6c46-4020-b117-b4eeccb49f33] received
jdi-qasp-ml-celery  | /usr/local/lib/python3.7/site-packages/celery/platforms.py:835: SecurityWarning: You're running the worker with superuser privileges: this is
jdi-qasp-ml-celery  | absolutely not recommended!
jdi-qasp-ml-celery  | 
jdi-qasp-ml-celery  | Please specify a different user using the --uid option.
jdi-qasp-ml-celery  | 
jdi-qasp-ml-celery  | User information: uid=0 euid=0 gid=0 egid=0
jdi-qasp-ml-celery  | 
jdi-qasp-ml-celery  |   uid=uid, euid=euid, gid=gid, egid=egid,
jdi-qasp-ml-celery  | [2022-03-28 07:01:10,672: INFO/ForkPoolWorker-3] Task app.tasks.task_schedule_xpath_generation[7acbac86-6c46-4020-b117-b4eeccb49f33] succeeded in 0.08645310000065365s: '//*[@class=\'InfinityFooter-tooltipContainer-vxD\']'
jdi-qasp-ml-celery  | [2022-03-28 07:01:11,209: INFO/MainProcess] Task app.tasks.task_schedule_xpath_generation[59b6ab08-afdd-4f63-8b0a-aded58eb8e77] received
jdi-qasp-ml-celery  | [2022-03-28 07:01:11,299: INFO/ForkPoolWorker-3] Task app.tasks.task_schedule_xpath_generation[59b6ab08-afdd-4f63-8b0a-aded58eb8e77] succeeded in 0.05854609999914828s: '//*[@class=\'InfinityFooter-footerLink-Sgi e2e-FooterInfinity-link-help\']'
jdi-qasp-ml-celery  | [2022-03-28 07:01:11,884: INFO/MainProcess] Task app.tasks.task_schedule_xpath_generation[69fae0e6-0f9f-44af-a18b-91283ea3d9b4] received
jdi-qasp-ml-celery  | [2022-03-28 07:01:11,969: INFO/ForkPoolWorker-3] Task app.tasks.task_schedule_xpath_generation[69fae0e6-0f9f-44af-a18b-91283ea3d9b4] succeeded in 0.06135849999918719s: '//*[@class=\'InfinityFooter-footerLink-Sgi e2e-FooterInfinity-link-privacy\']'
jdi-qasp-ml-celery  | [2022-03-28 07:01:12,515: INFO/MainProcess] Task app.tasks.task_schedule_xpath_generation[0f47cc09-8b52-418d-9807-43cd212baf1f] received
jdi-qasp-ml-celery  | [2022-03-28 07:01:12,588: INFO/ForkPoolWorker-3] Task app.tasks.task_schedule_xpath_generation[0f47cc09-8b52-418d-9807-43cd212baf1f] succeeded in 0.05084220000026107s: '//*[@class=\'InfinityFooter-footerLink-Sgi e2e-FooterInfinity-link-community\']'
jdi-qasp-ml-celery  | [2022-03-28 07:01:13,180: INFO/MainProcess] Task app.tasks.task_schedule_xpath_generation[4633cf2d-dfce-4540-90d0-ec2d4c3fe725] received
jdi-qasp-ml-celery  | [2022-03-28 07:01:13,258: INFO/ForkPoolWorker-3] Task app.tasks.task_schedule_xpath_generation[4633cf2d-dfce-4540-90d0-ec2d4c3fe725] succeeded in 0.05586849999963306s: '//*[@class=\'InfinityFooter-footerLinks-STj\']'
jdi-qasp-ml-celery  | [2022-03-28 07:01:13,795: INFO/MainProcess] Task app.tasks.task_schedule_xpath_generation[d4339e68-1e15-45a1-93e7-1cc6725f75fd] received
jdi-qasp-ml-celery  | [2022-03-28 07:01:13,871: INFO/ForkPoolWorker-3] Task app.tasks.task_schedule_xpath_generation[d4339e68-1e15-45a1-93e7-1cc6725f75fd] succeeded in 0.054831700001159334s: '//*[@class=\'InfinityFooter-tooltipMore-UjP\']'
jdi-qasp-ml-api     | WARNING:  Invalid HTTP request received.
jdi-qasp-ml-api     | Traceback (most recent call last):
jdi-qasp-ml-api     |   File "/usr/local/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 132, in data_received
jdi-qasp-ml-api     |     self.parser.feed_data(data)
jdi-qasp-ml-api     |   File "httptools/parser/parser.pyx", line 212, in httptools.parser.parser.HttpParser.feed_data
jdi-qasp-ml-api     | httptools.parser.errors.HttpParserInvalidMethodError: Invalid method encountered
jdi-qasp-ml-api     | WARNING:  Invalid HTTP request received.
jdi-qasp-ml-api     | Traceback (most recent call last):
jdi-qasp-ml-api     |   File "/usr/local/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 132, in data_received
jdi-qasp-ml-api     |     self.parser.feed_data(data)
jdi-qasp-ml-api     |   File "httptools/parser/parser.pyx", line 212, in httptools.parser.parser.HttpParser.feed_data
jdi-qasp-ml-api     | httptools.parser.errors.HttpParserInvalidMethodError: Invalid method encountered
jdi-qasp-ml-celery  | /usr/local/lib/python3.7/site-packages/celery/platforms.py:835: SecurityWarning: You're running the worker with superuser privileges: this is
jdi-qasp-ml-celery  | absolutely not recommended!
jdi-qasp-ml-celery  | 
jdi-qasp-ml-celery  | Please specify a different user using the --uid option.
jdi-qasp-ml-celery  | 
jdi-qasp-ml-celery  | User information: uid=0 euid=0 gid=0 egid=0
jdi-qasp-ml-celery  | 
jdi-qasp-ml-celery  |   uid=uid, euid=euid, gid=gid, egid=egid,
jdi-qasp-ml-celery  | [2022-03-28 07:01:20,041: INFO/ForkPoolWorker-1] Task app.tasks.task_schedule_xpath_generation[1f2830e1-97a3-4425-82e1-a292166f2293] succeeded in 10.244960500000161s: '/html/body/div[1]/div[1]/div/div[2]/div[1]/div/div[1]/div/div[1]/div[1]/div/ul/li[2]/div/div/div/div[1]/div[2]/div[1]/div[1]/div/span/a/img'
jdi-qasp-ml-celery  | [2022-03-28 07:01:20,307: INFO/ForkPoolWorker-4] Task app.tasks.task_schedule_xpath_generation[2e9027ba-6a24-4c99-8838-3ac68bf9b36b] succeeded in 10.056685900000957s: '/html/body/div[1]/div[1]/div/div[2]/div[1]/div/div[1]/div/div[1]/div[1]/div/ul/li[2]/div/div/div/div[1]/div[2]/div[1]/div[2]/div/span/a/img'
jdi-qasp-ml-celery  | [2022-03-28 07:01:20,700: INFO/ForkPoolWorker-2] Task app.tasks.task_schedule_xpath_generation[9cc48179-2dd8-4e82-ab0e-92f0b8a5abe5] succeeded in 10.202961299999515s: '/html/body/div[1]/div[1]/div/div[2]/div[1]/div/div[1]/div/div[1]/div[1]/div/ul/li[1]/div/div/div/div[1]/div[2]/div[1]/div/div/span/a/img'
jdi-qasp-ml-redis   | 1:M 28 Mar 2022 07:05:52.037 * 100 changes in 300 seconds. Saving...
jdi-qasp-ml-redis   | 1:M 28 Mar 2022 07:05:52.039 * Background saving started by pid 14
jdi-qasp-ml-redis   | 14:C 28 Mar 2022 07:05:52.054 * DB saved on disk
jdi-qasp-ml-redis   | 14:C 28 Mar 2022 07:05:52.055 * RDB: 0 MB of memory used by copy-on-write
jdi-qasp-ml-redis   | 1:M 28 Mar 2022 07:05:52.143 * Background saving terminated with success
jdi-qasp-ml-api     | ERROR:    Exception in ASGI application
jdi-qasp-ml-api     | Traceback (most recent call last):
jdi-qasp-ml-api     |   File "/usr/local/lib/python3.7/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 190, in run_asgi
jdi-qasp-ml-api     |     result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
jdi-qasp-ml-api     |   File "/usr/local/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
jdi-qasp-ml-api     |     return await self.app(scope, receive, send)
jdi-qasp-ml-api     |   File "/usr/local/lib/python3.7/site-packages/fastapi/applications.py", line 212, in __call__
jdi-qasp-ml-api     |     await super().__call__(scope, receive, send)
jdi-qasp-ml-api     |   File "/usr/local/lib/python3.7/site-packages/starlette/applications.py", line 112, in __call__
jdi-qasp-ml-api     |     await self.middleware_stack(scope, receive, send)
jdi-qasp-ml-api     |   File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 146, in __call__
jdi-qasp-ml-api     |     await self.app(scope, receive, send)
jdi-qasp-ml-api     |   File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 58, in __call__
jdi-qasp-ml-api     |     await self.app(scope, receive, send)
jdi-qasp-ml-api     |   File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 656, in __call__
jdi-qasp-ml-api     |     await route.handle(scope, receive, send)
jdi-qasp-ml-api     |   File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 315, in handle
jdi-qasp-ml-api     |     await self.app(scope, receive, send)
jdi-qasp-ml-api     |   File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 77, in app
jdi-qasp-ml-api     |     await func(session)
jdi-qasp-ml-api     |   File "/usr/local/lib/python3.7/site-packages/fastapi/routing.py", line 273, in app
jdi-qasp-ml-api     |     await dependant.call(**values)
jdi-qasp-ml-api     |   File "./app/robula_api.py", line 117, in websocket
jdi-qasp-ml-api     |     data = await ws.receive_json()
jdi-qasp-ml-api     |   File "/usr/local/lib/python3.7/site-packages/starlette/websockets.py", line 97, in receive_json
jdi-qasp-ml-api     |     message = await self.receive()
jdi-qasp-ml-api     |   File "/usr/local/lib/python3.7/site-packages/starlette/websockets.py", line 48, in receive
jdi-qasp-ml-api     |     'Cannot call "receive" once a disconnect message has been received.'
jdi-qasp-ml-api     | RuntimeError: Cannot call "receive" once a disconnect message has been received.
jdi-qasp-ml-api     | INFO:     connection closed

**Comment by ioffem** [comment]
JDN v 3.1.157
Back-end v 2022-03-30-06.47.33
Chrome

is not reproducible anymore. close.
