### ISSUE TITLE
Зависание бэка (воспроизведено локально)

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#591]
1. Открыть https://www.google.com/search?q=JDI&sxsrf=ALiCzsYK4OXgGkddFikQiE26rqF9fLiyTQ:1660053049422&source=lnms&tbm=isch&sa=X&ved=2ahUKEwidncbC87n5AhXhD1kFHbLZBbsQ_AUoAXoECAIQAw&biw=994&bih=747&dpr=2
2. Пролистать сильно вниз, до кнопки - Ещё результаты.
3. Нажать на кнопку - Ещё результаты
4. Открыть JDN и начать распознавать.
5. Система покажет покрытие, загрузит локаторы и навсегда зависнет в состоянии 0/1869 посчитанных локаторов
6. Лог сервера см. ниже

Начиная с этого момент - распознавание контролов на других страничках будет работать, а вот расчёт локаторов - уже никогда

alexey-api-1     | INFO:     Started server process [1]
alexey-api-1     | 09-Aug-22 19:33:25 - [INFO] - uvicorn.error - (server.py).serve(75) - Started server process [1]
alexey-api-1     | INFO:     Waiting for application startup.
alexey-api-1     | 09-Aug-22 19:33:25 - [INFO] - uvicorn.error - (on.py).startup(47) - Waiting for application startup.
alexey-api-1     | INFO:     Application startup complete.
alexey-api-1     | 09-Aug-22 19:33:25 - [INFO] - uvicorn.error - (on.py).startup(61) - Application startup complete.
alexey-api-1     | INFO:     Uvicorn running on http://0.0.0.0:5000 (Press CTRL+C to quit)
alexey-api-1     | 09-Aug-22 19:33:25 - [INFO] - uvicorn.error - (server.py)._log_started_message(212) - Uvicorn running on http://0.0.0.0:5000 (Press CTRL+C to quit)
alexey-api-1     | INFO:     172.20.0.1:50238 - "GET /build HTTP/1.1" 200 OK
alexey-api-1     | INFO:     172.20.0.1:50236 - "GET /download_template HTTP/1.1" 200 OK
alexey-api-1     | 09-Aug-22 19:34:31 - [INFO] - jdi-qasp-ml - (html5_predict.py).html5_predict_elements(20) - saving 20220809193431964955.json
alexey-api-1     | 09-Aug-22 19:34:31 - [INFO] - jdi-qasp-ml - (html5_predict.py).html5_predict_elements(25) - saving 20220809193431964955.pkl
alexey-api-1     | 09-Aug-22 19:34:32 - [INFO] - jdi-qasp-ml - (html5_predict.py).html5_predict_elements(34) - Creating JDNDataset
  0%|          | 0/1 [00:00<?, ?it/s, /jdi-qasp-ml/data/html509-Aug-22 19:34:33 - [INFO] - numba.core.transforms - (transforms.py)._extract_loop_lifting_candidates(57) - finding looplift candidates
alexey-api-1     |                                                   09-Aug-22 19:34:33 - [INFO] - numba.core.transforms - (transforms.py)._extract_loop_lifting_candidates(57) - finding looplift candidates
Build tree features: 100%|██████████| 7217/7217 [00:04<00:00, 1579.48it/s]
100%|██████████| 1/1 [00:15<00:00, 15.35s/it, /jdi-qasp-ml/data/html5_dataset/df/20220809193431964955.pkl]2022-08-09 19:34:47,427 -INFO - dataset.py:225 - self.df.shape: (7217, 30)
alexey-api-1     |
alexey-api-1     | 09-Aug-22 19:34:47 - [INFO] - utils.dataset - (dataset.py).build_primari_features_and_concatenate(225) - self.df.shape: (7217, 30)
alexey-api-1     | 2022-08-09 19:34:47,428 -INFO - dataset.py:108 - Check for duplicates...
alexey-api-1     | 09-Aug-22 19:34:47 - [INFO] - utils.dataset - (dataset.py).check_for_duplicates(108) - Check for duplicates...
alexey-api-1     | 2022-08-09 19:34:47,430 -INFO - dataset.py:112 - Check for duplicates is OK
alexey-api-1     | 2022-08-09 19:34:47,430 -INFO - dataset.py:229 - Calculating features...
alexey-api-1     | 09-Aug-22 19:34:47 - [INFO] - utils.dataset - (dataset.py).check_for_duplicates(112) - Check for duplicates is OK
alexey-api-1     | 09-Aug-22 19:34:47 - [INFO] - utils.dataset - (dataset.py).build_secondary_features(229) - Calculating features...
alexey-api-1     | 2022-08-09 19:34:47,673 -INFO - dataset_collector.py:178 - X: (7217, 79)
alexey-api-1     | 2022-08-09 19:34:47,673 -INFO - dataset.py:233 - Features have calculated succesfully!
alexey-api-1     | 09-Aug-22 19:34:47 - [INFO] - utils.dataset - (dataset_collector.py).collect_dataset(178) - X: (7217, 79)
alexey-api-1     | 09-Aug-22 19:34:47 - [INFO] - utils.dataset - (dataset.py).build_secondary_features(233) - Features have calculated succesfully!
alexey-api-1     | 09-Aug-22 19:34:47 - [INFO] - jdi-qasp-ml - (html5_predict.py).html5_predict_elements(41) - Loading the model
alexey-api-1     | /usr/local/lib/python3.7/site-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version 1.0.1 when using version 0.24.1. This might lead to breaking code or invalid results. Use at your own risk.
alexey-api-1     |   UserWarning)
alexey-api-1     | 09-Aug-22 19:34:48 - [INFO] - jdi-qasp-ml - (html5_predict.py).html5_predict_elements(52) - Predicting...
alexey-api-1     | INFO:     172.20.0.1:50248 - "POST /html5-predict HTTP/1.1" 200 OK
alexey-api-1     | INFO:     ('172.20.0.1', 50252) - "WebSocket /ws" [accepted]
alexey-api-1     | 09-Aug-22 19:34:54 - [INFO] - uvicorn.error - (websockets_impl.py).asgi_send(215) - ('172.20.0.1', 50252) - "WebSocket /ws" [accepted]
alexey-api-1     | INFO:     connection open
alexey-api-1     | 09-Aug-22 19:34:54 - [INFO] - uvicorn.error - (server.py).handshake(642) - connection open
alexey-api-1     | ERROR:    Exception in ASGI application
alexey-api-1     | Traceback (most recent call last):
alexey-api-1     |   File "/usr/local/lib/python3.7/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 184, in run_asgi
alexey-api-1     |     result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
alexey-api-1     |   File "/usr/local/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
alexey-api-1     |     return await self.app(scope, receive, send)
alexey-api-1     |   File "/usr/local/lib/python3.7/site-packages/fastapi/applications.py", line 269, in __call__
alexey-api-1     |     await super().__call__(scope, receive, send)
alexey-api-1     |   File "/usr/local/lib/python3.7/site-packages/starlette/applications.py", line 124, in __call__
alexey-api-1     |     await self.middleware_stack(scope, receive, send)
alexey-api-1     |   File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 149, in __call__
alexey-api-1     |     await self.app(scope, receive, send)
alexey-api-1     |   File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 69, in __call__
alexey-api-1     |     await self.app(scope, receive, send)
alexey-api-1     |   File "/usr/local/lib/python3.7/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
alexey-api-1     |     raise e
alexey-api-1     |   File "/usr/local/lib/python3.7/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
alexey-api-1     |     await self.app(scope, receive, send)
alexey-api-1     |   File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 670, in __call__
alexey-api-1     |     await route.handle(scope, receive, send)
alexey-api-1     |   File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 325, in handle
alexey-api-1     |     await self.app(scope, receive, send)
alexey-api-1     |   File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 81, in app
alexey-api-1     |     await func(session)
alexey-api-1     |   File "/usr/local/lib/python3.7/site-packages/fastapi/routing.py", line 279, in app
alexey-api-1     |     await dependant.call(**values)
alexey-api-1     |   File "./app/robula_api.py", line 132, in websocket
alexey-api-1     |     action, payload, ws, logging_info
alexey-api-1     |   File "./utils/api_utils.py", line 191, in process_incoming_ws_request
alexey-api-1     |     logging_info = LoggingInfoModel(**logging_info)
alexey-api-1     | TypeError: ModelMetaclass object argument after ** must be a mapping, not NoneType
alexey-api-1     | 09-Aug-22 19:34:54 - [ERROR] - uvicorn.error - (websockets_impl.py).run_asgi(188) - Exception in ASGI application
alexey-api-1     | Traceback (most recent call last):
alexey-api-1     |   File "/usr/local/lib/python3.7/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 184, in run_asgi
alexey-api-1     |     result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
alexey-api-1     |   File "/usr/local/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
alexey-api-1     |     return await self.app(scope, receive, send)
alexey-api-1     |   File "/usr/local/lib/python3.7/site-packages/fastapi/applications.py", line 269, in __call__
alexey-api-1     |     await super().__call__(scope, receive, send)
alexey-api-1     |   File "/usr/local/lib/python3.7/site-packages/starlette/applications.py", line 124, in __call__
alexey-api-1     |     await self.middleware_stack(scope, receive, send)
alexey-api-1     |   File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 149, in __call__
alexey-api-1     |     await self.app(scope, receive, send)
alexey-api-1     |   File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 69, in __call__
alexey-api-1     |     await self.app(scope, receive, send)
alexey-api-1     |   File "/usr/local/lib/python3.7/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
alexey-api-1     |     raise e
alexey-api-1     |   File "/usr/local/lib/python3.7/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
alexey-api-1     |     await self.app(scope, receive, send)
alexey-api-1     |   File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 670, in __call__
alexey-api-1     |     await route.handle(scope, receive, send)
alexey-api-1     |   File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 325, in handle
alexey-api-1     |     await self.app(scope, receive, send)
alexey-api-1     |   File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 81, in app
alexey-api-1     |     await func(session)
alexey-api-1     |   File "/usr/local/lib/python3.7/site-packages/fastapi/routing.py", line 279, in app
alexey-api-1     |     await dependant.call(**values)
alexey-api-1     |   File "./app/robula_api.py", line 132, in websocket
alexey-api-1     |     action, payload, ws, logging_info
alexey-api-1     |   File "./utils/api_utils.py", line 191, in process_incoming_ws_request
alexey-api-1     |     logging_info = LoggingInfoModel(**logging_info)
alexey-api-1     | TypeError: ModelMetaclass object argument after ** must be a mapping, not NoneType
alexey-api-1     | INFO:     connection closed
alexey-api-1     | 09-Aug-22 19:34:54 - [INFO] - uvicorn.error - (server.py).handler(260) - connection closed

**Comment by AlexeyGirin** [comment]
Была не релизная версия бэка (девовская, при том что должна была быть релизная) , поэтому оно работало неверно.
Инструкция была обновлена в Readme.md
